name: Automated Deployment to Dev

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'infra/**'

jobs:
  backend-dev:
    uses: ./.github/workflows/backend-dev.yaml
    secrets: inherit

  frontend-dev:
    uses: ./.github/workflows/frontend-dev.yaml
    secrets: inherit

