name: Automated Deployment to Dev

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'infra/**'

jobs:
  detect-changes:
      runs-on: ubuntu-latest
      outputs:
        backend: ${{ steps.changes.outputs.backend }}
        frontend: ${{ steps.changes.outputs.frontend }}
      steps:
        - name: Checkout PR source
          uses: actions/checkout@v4
          with:
            ref: refs/pull/${{ github.event.pull_request.number }}/merge
            fetch-depth: 0

        - name: Detect Changed Paths
          id: changes
          uses: dorny/paths-filter@v2
          with:
            list-files: shell
            filters: |
              backend:
                - 'infra/**'
              frontend:
                - 'frontend/**'

  backend-dev:
    needs: detect-changes
    uses: ./.github/workflows/backend-dev.yaml
    secrets: inherit

  frontend-dev:
    needs: detect-changes
    uses: ./.github/workflows/frontend-dev.yaml
    secrets: inherit

